name: voice_message_package
description: Flutter package to play/puase voice message in chat messengers.
version: 1.0.34
homepage: https://github.com/mehranshoqi/voice_message_player

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  just_audio: ^0.9.38
  syncfusion_flutter_sliders: ^25.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


